baseURL = 'https://luisbarajasr.github.io/luispage/'
languageCode = 'en-us'
title = 'luisbarajasr'
theme = 'archie'
copyright = "© luisbarajasr"

[params]
	mode = "auto" # color-mode → light,dark,toggle or auto
	subtitle = "I don't know where am I going, but im still moving."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/luisbarajasr"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/luisbarajasrmz/"

[[menu.main]]
name = "posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "wow"
url = "/wow"
weight = 2

[[menu.main]]
name = "thoughts"
url = "/thoughts"
weight = 3